- .github/workflows/check-release.yml
- src/BuildForRelease.ps1
- src/PackageRelease.ps1
Previously, we published everything to a single directory and released
all the executables together. With this change, different targets are
separately built (`AasxBlazor` and `AasxServerCore`, respectively) and
separately packaged for release.
The target `AasxServerWindows` could not be built due to an error
related to dependnencies and is still pending.
> Release separate bundles for Blazor and .NET core

- .github/workflows/check-release.yml
- src/.gitignore
- src/BuildForRelease.ps1
- src/PackageRelease.ps1
AasxServerWindows depends on .NET Framework, so it can not be built with
dotnet command. Hence, we build it with MSBuild in a separate step of
the build script.
> Build AasxServerWindows

- .github/workflows/check-release.yml
- src/BuildForRelease.ps1
- src/PackageRelease.ps1
The project `AasxBlazor` was renamed to `AasxServerBlazor`. This change
reflects this rename in continuous integration.
> Release AasxServerBlazor instead of AasxBlazor

- .github/workflows/check-release.yml
- src/BuildForRelease.ps1
- src/PackageRelease.ps1
So far, we built and released only binaries for Windows. With this
change, we also build and release binaries for Linux.
This is also relevant for releasing docker images in one of the next
commits.
> Build for both Windows and Linux

- src/AasxServerBlazor/startForDemo.bat
- src/AasxServerBlazor/startForDemo.sh
- src/AasxServerCore/startForDemo.bat
- src/AasxServerCore/startForDemo.sh
Serving OPC is not necessary for the demonstration, so we remove it.
Moreover, Windows does not support serving at host `0.0.0.0`, so that
argument is also removed.
> Fix startForDemo.bat's

- .github/workflows/build-and-publish-docker-images.yml
- README.md
- src/BuildDockerImages.ps1
This patch changes all the pointers to `mristin/*` dockerhub
repositories to `adminshellio/*` repositories.
Additionally, the suffix `-for-demo` is added to the images to allow for
distinction from production or experimental images in the future.
> Point to `adminshellio/*` docker repositories

- .github/workflows/check-release.yml
- README.md
- src/AasxServerBlazor/startForDemo.sh
- src/AasxServerCore/startForDemo.sh
- src/BuildForRelease.ps1
- src/PackageRelease.ps1
Including the CLR made the binary size bloat. This patch reverts the CI
configuration so that the CLR is excluded from the release. The dotnet
runtime is required on both Windows and Linux to run the releases.
> Remove runtimes from releases

- src/BuildForRelease.ps1
Build script copies recursively the content for demo to the respective
build directories for each target (AasxServerBlazor, AasxServerCore
*etc.*). Previously, the script mistakenly failed when the files already
existed.
> Force overwriting content for demo when building

- src/AasxServerBlazor/Data/AASService.cs
- src/AasxServerBlazor/Pages/TreePage.razor
- src/AasxServerBlazor/Program.cs
- src/AasxServerCore/Program.cs
- src/AasxServerStandardBib/AasxHttpContextHelper.cs
- src/AasxServerStandardBib/Program.cs
- src/AasxServerWindows/Program.cs
`Net46ConsoleServer` is a misnomer as the reader thinks this is some
kind of a general server. This patch renames it to `AasxServer` in order
to make it evidently more specific.
> Rename `Net46ConsoleServer` to `AasxServer`

- src/AasxServerStandardBib/Program.cs
The command line argument `-registry` has been deprecated since it
implied the dependence on Basyx library which created a dependency hell.
Additionally, unused imports were removed from the base AasxServer
Program for better readability.
> Remove `-registry` command-line argument

- README.md
- src/AasxServerBlazor/startForDemo.bat
- src/AasxServerBlazor/startForDemo.sh
- src/AasxServerCore/startForDemo.bat
- src/AasxServerCore/startForDemo.sh
This patch fixes the parts of the Readme and run-for-demo scripts which
were mistakenly omitted in a previous commit.
> Fix readme and demo scripts for command-line API

- README.md
- src/AasxServerStandardBib/Program.cs
This change attaches abbreviation aliases to a subset of command-line
options which are already familiar for the users (such as `-h` for
`--host`).
> Attach abbreviations to command-line options

- README.md
There were a couple of trailing spaces erroneously left in the readme
which makes diff'ing unnecessarily confusing.
The workflow build-and-publish-docker-images was intentionally skipped.
The workflow check-release was intentionally skipped.
> Remove trailing spaces in Readme

- README.md
- src/AasxServerBlazor/startForDemo.bat
- src/AasxServerBlazor/startForDemo.sh
- src/AasxServerCore/startForDemo.bat
- src/AasxServerCore/startForDemo.sh
- src/docker/Dockerfile-AasxServerBlazor
- src/docker/Dockerfile-AasxServerCore
This patch changes the dockerfiles so that they include the content
for demonstration and fixes the Readme so that the user are instructed
how to interact with the running container and how to copy additional
files for demonstration.
> Fix dockerfiles and documentation

- README.md
The copy command listed in the Readme had an error -- `docker cp` does
not support wildcards (`docker cp /some/path/*.aasx ...`). This patch
fixes the command so that it only copies the content of the directory
without any globbing with wildcards.
> Fix `docker cp` command in Readme

- CONTRIBUTING.md
- README.md
This patch introduces the article `CONTRIBUTING.md` which explains in
more detail the development workflow to future contributors.
The workflow build-and-publish-docker-images was intentionally skipped.
The workflow check-release was intentionally skipped.
> Write CONTRIBUTING.md

- README.md
So far we only have 6 docker images, so it is easier for the reader to
follow an explicit list than manually append the corresponing suffix.
We will hopefully make a proper multi-arch docker in the future.
> List explicitly docker images by architecture

- .github/workflows/build-and-publish-docker-images.yml
This patch makes the workflow for building and publishing docker images
run only if there are pushes to master or new releases. Previously, we
ran on every push which polluted DockerHub repository with unnecessary
images.
> Publish dockers only on master and releases

- src/docker/Dockerfile-AasxServerBlazor-arm32
- src/docker/Dockerfile-AasxServerBlazor-arm64
The dockerfile for ARM 32-bit and ARM 64-bit diverged since the former
used ASP.NET base image and the latter slim dotnet core image. Blazor
requires ASP.NET *runtime* and we had problems running Blazor
aasx-server on dotnet core base image.
> Unify ARM dockerfiles on ASP.NET for Blazor

- .github/workflows/build-and-publish-docker-images.yml
This patch fixes a minor typo (missing colon). The bug went unnoticed
since the workflow only runs on pushes to master.
> Fix invalid docker GitHub workflow

- README.md
- src/CheckHelpInReadme.ps1
- src/Script.CheckHelpInReadme/Folder.DotSettings
- src/Script.CheckHelpInReadme/Program.cs
- src/Script.CheckHelpInReadme/Script.CheckHelpInReadme.csproj
The script returned very uninformative message back to the user. This
was due to inexpressive nature of Powershell scripts. This patch
includes a rewrite to C# with much more informative error messages.
> Improve message in CheckHelpInReadme

- src/AasxServerBlazor/Properties/launchSettings.json
- src/AasxServerStandardBib/Program.cs
Make connect transfer of large files in several blocks
Also increase connect speed during block transfer
> Add connect block transfer

- src/AasxServerStandardBib/AasxFileInfo.cs
- src/AasxServerStandardBib/AasxHttpContextHelper.cs
- src/AasxServerStandardBib/AdminShellPackageEnv.cs
Hi Andreas,
I have adapted the function EvalPutAasxOnServer() in AasxHttpContextHelper.cs.
Now it is possible to load and instatiate an AAS-template by appending instancesIdentificationSuffix to identification.id and idShort of AAS, Asset and Submodels.
Regards,
Magnus
> Magnus redeker/its owl te dz rest instantiate aas template

- src/docker/Dockerfile-AasxServerBlazor
The docker image for the demo of the blazor server needs to rely on
ASP.NET, but we built it only on top of .NET runtime.
This patch rewires the blazor image to have ASP.NET runtime included.
> Make blazor docker rely on asp.net docker

- src/AasxServerBlazor/Properties/launchSettings.json
- src/AasxServerStandardBib/AasxHttpContextHelper.cs
Now rules can also be defined for targetObject submodElement
The rules in the element tree are:
The nearest elements in the tree up must not be a "deny" but an "allow" or nothing
No elements with "deny" are allowed in the subtree below
> Add security rules per submodel element

- README.md
The URLs in Section `Docker Containers for Demonstration` like e.g.  https://hub.docker.com/repository/docker/adminshellio/aasx-server-blazor-for-demo are used by logged in users on docker hub. The public available URL are like e.g. https://hub.docker.com/r/adminshellio/aasx-server-blazor-for-demo
> Fix URLs of Docker Containers

- src/AasxServerStandardBib/AasxHttpContextHelper.cs
- src/AasxServerStandardBib/AasxHttpContextHelperAmlExtensions.cs
- src/AasxServerStandardBib/AasxHttpContextHelperXlsExtensions.cs
- src/AasxServerStandardBib/AasxHttpContextHelperXmlExtensions.cs
- src/AasxServerStandardBib/AasxHttpContextHelperZipExtensions.cs
Previously, fragments were either not encoded at all (AML) or URL-encoded (XML, etc.). In order to be more compliant with the latest version of DotAAS Part 2 and facilitate decoding of fragments, all fragments now need to be Base64URL-encoded.
Base64URL-decoding is now done separately and the decoded fragment is passed to the type-specific routines.
> Base64URL-encoding for fragments

- src/AasxServerStandardBib/AasxHttpContextHelper.cs
A small addition to add the definitions and preferred names of concept descriptions to the output of the `/aas/(id)/cds/` REST call.
Also fixes a bug when requesting an AAS by ID that was not found.
> Include embeddedDataSpecifications

- src/AasxServerStandardBib/AasxHttpContextHelper.cs
- src/AasxServerStandardBib/AasxHttpContextHelperXmlExtensions.cs
- src/AasxServerStandardBib/AasxHttpContextHelperZipExtensions.cs
- src/AasxServerStandardBib/AasxRestServer.cs
This adds support for nested fragments, i.e. repeated sequences of .../fragments/<fragment-type>/<fragment-value>/fragments/<...>/...>/...
A first implementation is provided for Zip files so that the rest API can now be used to query files inside Zip files (inside an AAS).
> Support for nested fragments

- src/AasxServerStandardBib/AdminShellPackageEnv.cs
- src/IO.Swagger.V1RC03/Services/AasxFileServerInterfaceService.cs
Issue: When the AASXPackage was updated via AASXFileServerInterface, the Blazor Tree structure used to break. 
Root cause: The new AASXPackage was loaded into AdminShellPackageEnv, however, the parents of the corresponding SubmodelElements were not being set. 
Fix: Setting the parent for all the SubmodelElements, after loading this updated AASXPackage.
> Minor bug fixes w.r.t. PutAASXPackage

- src/AasxCsharpLibrary/Extensions/ExtendConceptDescription.cs
- src/AasxServerBlazor/Properties/launchSettings.json
- src/AasxServerBlazor/startForDemo.bat
- src/AasxServerBlazor/startForDemo.sh
- src/AasxServerStandardBib/Program.cs
This PR includes fixes for GitHub Issues #220 and #222. 
[a] If a V2 AASX file consists of a concept description with empty IsCaseOf reference, V3 conversion and thereby file APIs fail due to constraints in xml de/serializations from aas-core-sdk. Thus, if V1 or V2 AASX files have such empty IsCaseOf reference, there are skipped from the conversion.
[b] Additionally, the server was showing a few command line arguments (-h, -p, -rest, -https, -external-rest ), which are not supported anymore. Hence, with this PR such arguments are removed.
[a] was successfully tested with GetAASXFile Api
[b] was tested with commandline execution of server with help option.
> Fix for GitHub Issues 220 and 222

- .github/changelog_configuration.json
- .github/workflows/code-analysis.yml
- .github/workflows/prerelease-on-merge-to-main.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- src/AasCore.Aas3_0/AasCore.Aas3_0.csproj
- src/AasSecurity/AasSecurity.csproj
- src/AasxCsharpLibrary/AasxCsharpLibrary.csproj
- src/AasxServer.sln
- src/AasxServerAspNetCore/AasxServerAspNetCore.csproj
- src/AasxServerBlazor/AasxServerBlazor.csproj
- src/AasxServerStandardBib/AasxServerStandardBib.csproj
- src/DataTransferObjects/DataTransferObjects.csproj
- src/ExampleClient/ExampleClient.csproj
- src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj
- src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
- src/es6numberserializer/es6numberserializer.csproj
- src/jsoncanonicalizer/jsoncanonicalizer.csproj
This PR addresses several improvements to our GitHub workflows, release creation process, and documentation to enhance clarity and functionality across the project. Changes include:
- Improved CONTRIBUTING.md and README.md to reflect the latest release workflow changes.
- Updated changelog configuration for accuracy and consistency.
- Revised labels and categories to align with GitHub labels.
- Enhanced readability of workflows and jobs through comments and renaming.
- Transitioned the latest build workflow to a nightly build, ensuring it checks for changes before creating a new latest build, which can also be manually triggered.
- Added a security policy in the form of SECURITY.md.
The changes have been tested by validating each updated workflow, ensuring proper label management, and …
> Fix GitHub Workflows and Release Creation, and Adapt Documentation

- src/AasxCsharpLibrary/AasxCompatibilityModels/V20/AdminShell.cs
This pull request addresses the thread-unsafe use of a static `ICryptoTransform` field. The original code used a static instance of `System.Security.Cryptography.SHA256`, which is not thread-safe and could lead to potential issues when accessed concurrently by multiple threads.  [Code analysis](https://github.com/eclipse-aaspe/server/security/code-scanning/2342)
To resolve this, the static instance has been replaced with a method that creates a new instance of `SHA256` whenever it is needed. This ensures that each thread operates on its own instance, thus maintaining thread safety.
This change is required to prevent potential thread safety issues that arise from the concurrent use of a shared `SHA256` instance. By creating a new instance for each thread, we ensure the integrity and …
> Fix Thread-unsafe use of a static ICryptoTransform field

- src/AasSecurityTests/AasSecurityTests.csproj
- src/AasxCsharpLibrary/AasxCsharpLibrary.csproj
- src/AasxServerAspNetCore/AasxServerAspNetCore.csproj
- src/AasxServerBlazor/AasxServerBlazor.csproj
- src/AasxServerDB/AasxServerDB.csproj
- src/AasxServerStandardBib/AasxServerStandardBib.csproj
- src/AasxServerStandardBib/Credentials.cs
- src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj
- src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
not all packages are valid with net8.0 and there are no current alternatives.
So far these are:
- GrapeVine
- QrCoder
- OPCFoundation.NetStandard.Opc.Ua
> Upgrade most packages to net8.0 compatibility 

- src/IO.Swagger.Lib.V3/Controllers/AssetAdministrationShellRepositoryAPIApi.cs
- src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
- src/IO.Swagger.Lib.V3/Formatters/AasRequestFormatter.cs
- src/IO.Swagger.Lib.V3/Middleware/ExceptionMiddleware.cs
- src/IO.Swagger.Lib.V3/Models/ReferencePagedResult.cs
This PR consists of fixes for the bugs found during API validation with aas-test-engine.
This change is required for the correct implementation of the APIs
1. In case of POST APIs, if the request body has serialization issues, the server now sends BadRequest (earlier Internal Server Error).
2. In case of API GET "/shells/$reference", if there are no shells present, server used to throw InternalServerError, due to null pointer exception. The issue has been now fixed. The server in this case now return empty Result.
The fixes are tested manually with the help of in-buit swagger-ui and with aas-test-engine.
> Fix bugs w.r.t. test-engine

- src/IO.Swagger.Lib.V3/Exceptions/InvalidPaginationParameterException.cs
- src/IO.Swagger.Lib.V3/Middleware/ExceptionMiddleware.cs
- src/IO.Swagger.Lib.V3/Models/PaginationParameters.cs
This PR consists of fixes for issue with negative PaginationParameter "Limit".
This change is required for the correct implementation of the APIs. With this fix, the server now returns "BadRequest" if a negative integer is provided as Limit.
#333 
The fixes are tested manually with the help of in-buit swagger-ui and with aas-test-engine.
> Fix the issue 333

- src/IO.Swagger.Lib.V3/Converters/ServiceProfileEnumValueConverter.cs
- src/IO.Swagger.Lib.V3/Models/ServiceDescription.cs
This PR fixes the serialization issue w.r.t. ServiceProfiles in case of DescriptionAPI.
The previous implementation used "JsonEnumStringConverter" in case of ServiceProfile serializations. However, this converter only takes EnumNames instead of numbers while serializing. However, the values provided by EnumMember attribute here are import. Thus, this PR provides a custom convert which takes values of the enums in serialization.
The issue and corresponding changes have tested manually with the help of swagger-ui.
> Fix serialization of ServiceProfiles

- src/AasxServerBlazor/Configuration/ServerConfiguration.cs
- src/IO.Swagger.Lib.V3/Controllers/DescriptionAPIApi.cs
This PR adds a constructor based on IServiceDscription in the corresponding controller to fix the broken test pipeline.
The unit tests written for Self-description API requires a injection of IServiceDescription in DescriptionAPIController. The injection was removed in earlier fix, therefore the tests no longer worked. Hence, bringing it back with this PR.
Manual testing, if the API works as expectation.
> Add constructor to ServiceDescription API

- src/IO.Swagger.Lib.V3/Controllers/AASXFileServerAPIApi.cs
- src/IO.Swagger.Lib.V3/Formatters/AasResponseFormatter.cs
Fixing the issue related to the API GetAllPackages from AASXFileServerInterface.
This change fixes the broken GetAllPackages (\packages) operation from AASXFileServerInterface,
Manually and with AASX Package Explorer.
> Fix for \packages endpoint

- src/AasxServerStandardBib/Interfaces/IAdminShellPackageEnvironmentService.cs
- src/AasxServerStandardBib/Interfaces/ISubmodelService.cs
- src/AasxServerStandardBib/Services/AdminShellPackageEnvironmentService.cs
- src/AasxServerStandardBib/Services/SubmodelService.cs
- src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
This PR removes the query parameter "aasIdentifier" from POST /submodels endpoint, so as to make it conformant with the specifications and make it interoperable with other solutions.
Fixes #369 
Tested manually with Swagger UI.
> Remove "aasIdentifier" from POST /submodels
