eclipse-aaspe/server

.github/workflows/check-style.yml, .gitignore, src/.config/dotnet-tools.json, src/Check.ps1, src/CheckFormat.ps1, src/Common.psm1, src/FormatCode.ps1
This pactch includes scripts that re-format the code and adds format
check to the continuous integration.
=> Introduce dotnet-format to continuous integration

.github/workflows/check-release.yml, README.md, src/AasxServerStandardBib/AasxServerStandardBib.csproj, src/AasxServerStandardBib/Program.cs, src/Check.ps1, src/CheckHelpInReadme.ps1
The parsing of command-line arguments were previously done by an ad-hoc,
iterative logic over the arguments and manual parsing. This patch
introduces `System.CommandLine` to parse the arguments automatically in
a principled manner.
As an additional benefit, the `--help` overview is automatically
generated.
=> Use command-line API

src/AasxServerStandardBib/Program.cs
This patch makes the program pause if no arguments were supplied so that
the user is informed about the options. Otherwise, it would have been
very confusing for the user if the program immediately exits.
=> Pause execution if started from Windows Explorer

src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerStandardBib/AasxHttpContextHelper.cs, src/AasxServerStandardBib/AasxServerStandardBib.csproj, src/AasxServerStandardBib/Program.cs, src/AasxServerWindows/AasxServerWindows.csproj, src/AasxServerWindows/App.config, src/AasxServerWindows/packages.config
Before an error occurred when no token was passed with security enabled.
Now a redirect to the authServer in REDIRECT.DAT is done when a token is needed.
=> Add redirect

src/AasxServerStandardBib/i40Language.cs
This patch re-formats the code since there were problems on the
contributor's local machine.
=> Format code

src/AasxServer.sln, src/AasxServerBlazor/Data/AASService.cs, src/AasxServerBlazor/Pages/TreePage.razor, src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerStandardBib/AasxServerStandardBib.csproj, src/AasxServerStandardBib/Program.cs, src/AasxServerStandardBib/i40Language.cs
Remote connection by REST "connect"
=> Update i40 language

src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerCore/Properties/launchSettings.json, src/AasxServerStandardBib/AasEntityBuilder.cs, src/AasxServerStandardBib/AasNodeManager.cs, src/AasxServerStandardBib/AasUaEntities.cs, src/AasxServerStandardBib/AasUaEntities.cs.bak, src/AasxServerStandardBib/AasUaEntityFileType.cs, src/AasxServerStandardBib/AasxHttpContextHelper.cs, src/AasxServerStandardBib/AasxRestServer.cs, src/AasxServerStandardBib/AasxServerStandardBib.csproj, src/AasxServerStandardBib/AdminShell.cs, src/AasxServerStandardBib/AdminShellUtil.cs.bak, src/AasxServerStandardBib/AdminShellValidate.cs, src/AasxServerStandardBib/LogInternally.cs, src/AasxServerStandardBib/Program.cs, src/AasxServerStandardBib/SampleServer.cs
Put /server/getaasx for updated .AASX
Recursive online value retrieval
Update SDK according to Package Explorer
=> Add put aasx

src/AasxServerBlazor/Pages/TreePage.razor, src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerStandardBib/AasxHttpContextHelper.cs, src/AasxServerStandardBib/AasxRestServer.cs
Either a human readable page or the .AASX is provided
=> Add get AASX by AssetId

src/docker/Dockerfile-AasxServerBlazor, src/docker/Dockerfile-AasxServerBlazor-arm32, src/docker/Dockerfile-AasxServerBlazor-arm64, src/docker/Dockerfile-AasxServerCore, src/docker/Dockerfile-AasxServerCore-arm32, src/docker/Dockerfile-AasxServerCore-arm64
Microsoft updated the docker images due to the release of .NET 5.
See https://github.com/dotnet/dotnet-docker/issues/2375
=> Update base docker images

src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerStandardBib/AasxHttpContextHelper.cs
Further features for security model
=> Add security meta model

README.md
Basic API documentation added.
=> Add basic API documentation to README.md

src/AasxServerStandardBib/AasxRestServer.cs
An easy to use API to get changes by clients
=> Add DIFFJSON

.github/workflows/check-release.yml, .github/workflows/check-style.yml
Otherwise no external pull requests are possible
=> Actions should execute on pull requests as in AASXPackageExplorer

src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerStandardBib/AasxHttpContextHelper.cs
New query parameter ?json-ld=1 to GET
Used for verifiable credentials
=> Add output as JSON-LD

src/AasxServerStandardBib/AasxHttpContextHelper.cs, src/AasxServerStandardBib/AasxHttpContextHelperXlsExtensions.cs, src/AasxServerStandardBib/AasxHttpContextHelperXmlExtensions.cs, src/AasxServerStandardBib/AasxHttpContextHelperZipExtensions.cs, src/AasxServerStandardBib/AasxServerStandardBib.csproj
This adds REST routes and fragment evaluation for XML, XLS, and ZIP fragments
=> Add REST route and fragment evaluation for XML, XLS, and ZIP fragments

src/AasxServerBlazor/Properties/launchSettings.json, src/AasxServerStandardBib/AasxHttpContextHelper.cs, src/AasxServerStandardBib/AasxHttpContextHelperAmlExtensions.cs, src/AasxServerStandardBib/AasxHttpContextHelperXlsExtensions.cs, src/AasxServerStandardBib/AasxHttpContextHelperXmlExtensions.cs, src/AasxServerStandardBib/AasxHttpContextHelperZipExtensions.cs, src/AasxServerStandardBib/AasxRestServer.cs, src/AasxServerStandardBib/AasxServerStandardBib.csproj, src/AasxServerStandardBib/AdminShellPackageEnv.cs
Browse into AML files inside AAS model
=> Add AML fragments

src/AasxServerBlazor/Properties/launchSettings.json, src/IO.Swagger.V1RC03/APIModels/Core/OutputModifierContext.cs, src/IO.Swagger.V1RC03/APIModels/Core/PathTransformer.cs, src/IO.Swagger.V1RC03/Controllers/AssetAdministrationShellEnvironmentAPIApi.cs, src/IO.Swagger.V1RC03/Controllers/IAssetAdministrationShellEnvironmentAPIApi.cs, src/IO.Swagger.V1RC03/IO.Swagger.V1RC03.xml, src/IO.Swagger.V1RC03/Services/AssetAdministrationShellEnvironmentService.cs
Query parameter ?diff=time
Filter response
Only elements after time returned
=> Add diff for SubmodelElements

src/AasxServerStandardBib/AasxHttpContextHelper.cs, src/AasxServerStandardBib/AasxHttpContextHelperXmlExtensions.cs, src/AasxServerStandardBib/AasxHttpContextHelperZipExtensions.cs, src/AasxServerStandardBib/AasxRestServer.cs
Reverts admin-shell-io/aasx-server#150
=> Revert "Support for nested fragments"

src/AasxServerBlazor/Program.cs, src/AasxServerBlazor/Startup.cs
Hi Andreas,
here are a couple of lines to fix CORS in masterV3 version.
BR
Sten
=> Refactoring CORS to (again) accept requests from all hosts

src/AasxCsharpLibrary/AdminShellPackageEnv.cs, src/AasxServerBlazor/Properties/launchSettings.json
Took over the changes regarding the new namespace and its backwards compatibility from AASPE.
@juileetikekar I would be glad if you could take an extra look over it.
=> Namespace fix

CONTRIBUTING.md, README.md
I updated the links to the Contributing and contributors files and updated the wording and structure of some sentences
=> README and CONTTRIBUTING: add links and fix wording

src/docker/Dockerfile-AasxServerBlazor
Docker image now includes curl and nano
curl is necessary for the healthchecks
docker build and run
=> image now includes curl and nano

.github/workflows/prerelease-on-merge-to-main.yml
=> Update nightly workflow for more accurate release notes

.github/workflows/draft-prerelease-on-pushed-tag.yml, .github/workflows/draft-release-on-merge-to-release-branch.yml
=> Fix Release and develop workflow as well

.github/changelog_configuration.json, .github/workflows/build-and-publish-docker-images.yml, .github/workflows/draft-prerelease-on-pushed-tag.yml, .github/workflows/draft-release-on-merge-to-release-branch.yml, .github/workflows/prerelease-on-merge-to-main.yml, src/BuildVersionNumber.ps1
Fix issues in workflow version numbers and changelog creation.
=> Fix Workflow issues with release number and changelog 

.github/changelog_configuration.json, .github/workflows/create-developer-prerelease.yml, .github/workflows/draft-prerelease-on-pushed-tag.yml, .github/workflows/draft-release-on-merge-to-release-branch.yml, .github/workflows/prerelease-on-merge-to-main.yml, src/AasxServer.sln
=> Fix inconvenient bugs in workflows

src/AasxServerBlazor/Shared/MainLayout.razor
Fix the styling of PCF2 layout. There should not be an additional flex tag
=> fix styling of MainLayout.razor

.github/workflows/build-and-publish-docker-images.yml
=> Fix release docker workflow

.github/workflows/check-release.yml, .github/workflows/prerelease-on-merge-to-main.yml, .github/workflows/test-report.yml, src/.editorconfig, src/AasSecurity/AssemblyInfo.cs, src/AasSecurityTests/AasSecurityContextTest.cs, src/AasSecurityTests/AasSecurityTests.csproj, src/AasSecurityTests/GlobalUsings.cs, src/AasxServer.sln
=> Create unit test project and add it into process to run in every build

README.md
=> Add badge for dotnet version README.md

src/AasxServer.sln, src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj, src/IO.Swagger.Registry.Lib.V3.Tests/GlobalUsings.cs, src/IO.Swagger.Registry.Lib.V3.Tests/IO.Swagger.Registry.Lib.V3.Tests.csproj, src/IO.Swagger.Registry.Lib.V3.Tests/Services/AasDescriptorPaginationServiceTests.cs, src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
=> Add tests for IO.Swagger.Registry.Lib.V3

.github/workflows/check-release.yml, .github/workflows/code-analysis.yml, .github/workflows/create-developer-prerelease.yml, .github/workflows/draft-release-on-merge-to-release-branch.yml, README.md, src/global.json
=> update existing references to dotnet 8

src/AasCore.Aas3_0/AasCore.Aas3_0.csproj, src/AasSecurity/AasSecurity.csproj, src/AasSecurityTests/AasSecurityTests.csproj, src/AasxCsharpLibrary/AasxCsharpLibrary.csproj, src/AasxServer.sln, src/AasxServerAspNetCore/AasxServerAspNetCore.csproj, src/AasxServerBlazor/AasxServerBlazor.csproj, src/AasxServerBlazor/BlazorServerStarter.cs, src/AasxServerBlazorTests/AasxServerBlazorTests.csproj, src/AasxServerBlazorTests/Configuration/DependencyRegistryTests.cs, src/AasxServerBlazorTests/GlobalUsings.cs, src/AasxServerDB/AasxServerDB.csproj, src/AasxServerStandardBib/AasxServerStandardBib.csproj, src/DataTransferObjects/DataTransferObjects.csproj, src/es6numberserializer/es6numberserializer.csproj
=> Create new testing project for AasxServerBlazor

CHANGELOG.md
=> Add release notes of previous releases to CHANGELOG.md

src/docker/Dockerfile-AasxServerBlazor, src/docker/docker-compose-demo.yaml
=> Fix missing port exposing in docker container which preventer Blazor Ui from being shown

src/docker/Dockerfile-AasxServerBlazor, src/docker/docker-compose-demo.yaml, src/docker/docker-compose.yaml
=> fix docker build steps and ports for dotnet 8.0

src/AasxServerBlazor/BlazorServerStarter.cs, src/AasxServerBlazor/Configuration/ServerConfiguration.cs, src/docker/Dockerfile-AasxServerAspNetCore, src/docker/Dockerfile-AasxServerBlazor, src/docker/docker-compose-demo.yaml, src/docker/docker-compose.yaml
=> Fix docker ports on the build and default port

src/AasxServerAspNetCore/Startup.cs, src/AasxServerBlazor/Configuration/DependencyRegistry.cs
=> Add missing service registrations from RegistryInitializerService

src/IO.Swagger.Registry.Lib.V3/Services/RegistryInitializerService.cs
=> Fix nullable issue in RegistryInitializerService

src/IO.Swagger.Registry.Lib.V3/Services/RegistryInitializerService.cs
=> Add missing nullcheck for RegistryInitService

src/AasxServerStandardBib/Interfaces/IAdminShellPackageEnvironmentService.cs, src/AasxServerStandardBib/Interfaces/ISubmodelService.cs, src/AasxServerStandardBib/Services/AdminShellPackageEnvironmentService.cs, src/AasxServerStandardBib/Services/SubmodelService.cs, src/IO.Swagger.Lib.V3.Tests/Services/GenerateSerializationServiceTests.cs, src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
=> Fix nullables for submodelIdentifier and idShortpath in SubmodelRepositoryAPIApi.cs
